### ISSUE TITLE
Need method to get the Object URL to download the image/file anytime.

### ISSUE THREAD

**Issue by Anuradha677** [googleapis/nodejs-storage#1062]
Hi Team,

I am going to store the image/file URL in Cloud SQL and using that URL I can download the image from cloud storage anytime. I require both Private URL and Public URL.  If it is Private , then it should contain who can access the file and Public URL can download by anyone.

Thanks in advance. If there are any methods available already. Please do reply. I didn't find anything to do this.

**Comment by jkwlui** [comment]
For a public URL, you can use [file.getSignedUrl()](https://googleapis.dev/nodejs/storage/latest/File.html#getSignedUrl) to generate a temporary signed URL.

For the private URL, can you explain a little bit about how you intend to grant access and how would the user/application be downloading the file? Since limiting access would require some form of authentication, the easiest way would be to use this client library to download a file, rather than downloading via a URL.

**Comment by abutreca** [comment]
For private URL theres a link inside the object you get when you execute file.getFiles under metadata.medialink but you need auth for that.

**Comment by jkwlui** [comment]
Hi @Anuradha677, since we haven't heard back from you, I'd gone ahead and closed this issue. Please let us know if the suggested solution does not work for your intended use case by reopening this issue. Thanks!
