### ISSUE TITLE
add startOffset, endOffset and includeTrailingDelimiter in Get file options

### ISSUE THREAD

**Issue by laljikanjareeya** [googleapis/nodejs-storage#1271]
Similar case found in java as well see  https://github.com/googleapis/java-storage/issues/424 
check the [JSON](https://cloud.google.com/storage/docs/json_api/v1/objects/list#http-request) API for more info.
This also added `includeTrailingDelimiter` options to `GetFilesOptions`.

**Comment by stephenplusplus** [comment]
Let me know if I'm mistaken, but we do actually support the user passing `startOffset` and `endOffset`, but TypeScript users don't see it as an accepted parameter because it's not listed in the `GetFilesOptions` interface. This is an unfortunate thing about TypeScript compliance-- we designed the API to be as transparent as possible, in that we will accept anything the upstream API does, but TypeScript kind of forces us into a whitelist model where we have to be explicit about each property. There are probably many cases of leaks like this across our APIs, where we're not listing 1:1 parameters that are accepted. And I don't think that should be the goal, as we'd eventually go stale and list a property that has been deprecated or overlook a property that was recently added, either misleading or blocking the user, as we are in this case.

Anyway 😄  I don't think there's much we can do about this. Please let me know if I'm incorrect about any of that, or if there's another way to solve the problem.

P.S. I found we're missing `includeTrailingDelimiter` as well. While you're in there, want to add that in as well?

**Comment by laljikanjareeya** [comment]
@stephenplusplus you are right. I fully agree with you Thanks 👍
