### ISSUE TITLE
Retry Strategy should be enabled by default for multipart uploads

### ISSUE THREAD

**Issue by frankyn** [googleapis/nodejs-storage#1281]
1) Is this a client library issue or a product issue?
Library issue, that does not enable retries for multipart uploads and requires enabling retries automatically using `autoRetry: true`. Resumable uploads does support retries by default so there's an inconsistency here. I don't see any issue with enabling autoRetry by default for multipart uploads.

cc: @crwilcox @dmahugh

Internal bug: 166293186

2) Did someone already solve this?
The workaround is to enable retries doing the following:

```javascript
// Imports the Google Cloud client library
const {Storage} = require('@google-cloud/storage');

// Your Google Cloud Platform project ID
const projectId = 'project-id';

// Creates a client
const storage = new Storage({
  projectId: projectId,
});

// The name for the new bucket
const bucketName = 'bucket-name';
const contents = 'This is the contents of the file.';

storage
  .bucket(bucketName)
  .file('test')
  .save(contents, {
      autoRetry: true, // <<-- required to enable retries for multipart.
      resumable: false, // means, use multipart upload instead of resumable upload.
      }, function(err) {
    if (!err) {
      // File written successfully.
      console.log("File was written!");
    }
  });
```

#### Environment details

  - Node.js version: 12.7.0
  - `@google-cloud/storage` version: 5.3.0

**Comment by stephenplusplus** [comment]
Good point! Here's a description of what we need to do to enable this, from https://github.com/googleapis/nodejs-storage/issues/833#issuecomment-557691383:

Our uploads all use our streaming API underneath the surface, so `file.save(blob)` is akin to `file.createWriteStream({resumable:false}).end(blob)`. The streaming APIs are not able to resend data after a response from the server-- it can only do that if there was an issue preflight. Once data goes out from a stream, we can't rewind it arbitrarily to get it back.

However, I don't think there's a reason `file.save()` *needs* to use the streaming API underneath. We can just send the request like any other, putting the blob in the request body. Then, it would benefit from our normal exponential retry logic.

I'll assign myself and make the switch over to multipart uploads for `file.save()` rather than streaming.

Side note, `autoRetry` should not have an effect here 😕

**Comment by stephenplusplus** [comment]
Related: https://github.com/googleapis/nodejs-storage/issues/1233
