### ISSUE TITLE
fs.constants is undefined on node.js 12.18.3

### ISSUE THREAD

**Issue by Watcharagorn** [googleapis/nodejs-storage#1297]
I already try on node.js version 14.10.1 (lastest)

//  an error when i try to upload image to store

![image](https://user-images.githubusercontent.com/58912904/93011976-29b0be00-f5c6-11ea-82f3-7748d3dbb92c.png)

// in file.js
![image](https://user-images.githubusercontent.com/58912904/93011989-4b11aa00-f5c6-11ea-93e6-d0ab5e4f75bd.png)

// my upload function
![image](https://user-images.githubusercontent.com/58912904/93012457-bbbac580-f5ca-11ea-87d3-112f46ea3e5e.png)

**Comment by laljikanjareeya** [comment]
@Watcharagorn Thanks for reporting!!

I run code snippet given above with given version. it woks fine I am not able to reproduce it.

`fs.constants.W_OK` been there since Node <v6.3.0 earlier version it was like `fs.W_OK` and `storage` supports >v8.0.0 it should not be a problem.

Can you provide some more information about your environment?

**Comment by stephenplusplus** [comment]
@laljikanjareeya since we can't reproduce, I'm going to close. Hoping you got it sorted out!

**Comment by bobhollon** [comment]
I cam across this issue researching the same problem.
I can confirm complaint on v12.90.0, however only with promises deconstructed. 

require('fs').promises; --> fs.constants is undefined
require('fs'); ==> fs.constants is available

I use promises without callbacks.
I'm curious if promises is same issue as OP.
