### ISSUE TITLE
Promote env var usage instead of JSON file for auth

### ISSUE THREAD

**Issue by nikita-fuchs** [googleapis/nodejs-storage#1727]
Currently, in various places of the gcloud cloud storage documentation, following code is recommended to initialise the storage:

```
//Create a client with explicit credentials

const storage = new Storage({
  projectId: 'your-project-id',
  keyFilename: '/path/to/keyfile.json'
});
```

See: https://googleapis.dev/nodejs/storage/latest/Storage.html#Storage-examples

Making code rely on credentials stored in files is a bad practice from a security point of view, requires extra steps in kubernetes like mounting drives in runtime, also if builders/transpilers are used, the file needs to be copied around for the path to match.

From looking at the code, I got a solution working by providing the service account credentials directly, which I would kindly ask to promote in the docs instead:

Example:

```
 storage = new Storage({
    projectId: process.env.GCLOUD_PROJECT_ID,
    credentials: {
      client_email: process.env.GCLOUD_STORAGE_SERVICE_ACCOUNT_CLIENT_EMAIL,
      private_key: process.env.GCLOUD_STORAGE_SERVICE_ACCOUNT_PRIVATE_KEY
    }
  });
```

Environment variables are easier and safer to handle and exist in nearly every project, so it's trivial to put the service account details there simply, instead of handling that additional JSON file that could potentially leak.

Cheers

**Comment by andrewsg** [comment]
I agree that using a file could be suboptimal, but if I understand correctly we do not recommend the use of env variables for this purpose either. We instead suggest the use of a secure keystore such as Cloud Key Management. I think that might be too complex to integrate with our samples, so we should just aim for consistency with other Cloud samples; for now I'll assign to a language owner for a second opinion.

**Comment by shaffeeullah** [comment]
Hi @nikita-fuchs ,

Our samples aim to show the simplest way to perform an operation. In order to simplify the authentication, piece we show JSON file example. Different authentication strategies are appropriate in different scenarios. We have full documentation on authenticating with Cloud Storage [here](https://cloud.google.com/storage/docs/authentication).

**Comment by SpencerKaiser** [comment]
I 100% agree with @nikita-fuchs and think the use of a JSON file is something that will inevitably lead to security breaches because it's an anti-pattern for 99% of secrets in Node.js and most projects are not configured to ignore json files. 

I also disagree that using a json file is "the simplest way to perform an operation"; I'm here because I thought it was a mistake that the README doesn't mention how to auth with environment variables...
