### ISSUE TITLE
Security vulnerability with node-fetch version <3.1.1

### ISSUE THREAD

**Issue by vinaymehta1860** [googleapis/nodejs-storage#1861]
Hi all, I see that this package is using `node-fetch` v2.2.0 and there is a DoS security vulnerability ([source](https://www.sourceclear.com/vulnerability-database/security/denial-of-service-dos/javascript/sid-26730)) reported with that package which was fixed in versions >=3.1.1. Can this dependency be updated to version >=3.1.1 so that clients for whom `node-fetch` is getting installed as a transitive dependency via google-cloud/storage can get the right version for `node-fetch` installed on their machine?

Thank you!

**Comment by ddelgrosso1** [comment]
Hi @vinaymehta1860 thanks for bringing this to our attention. You are correct, we are utilizing an older version of `node-fetch`. However, it is only a dev dependency used for tests and not part of the released package. I will be updating it to version `2.6.7` which appears to have the vulnerability fixed. Unfortunately at this time moving to `3.x` is not possible because `node-fetch` has gone to pure ESM.
