### ISSUE TITLE
UploadOptions mutates provided object

### ISSUE THREAD

**Issue by sethvargo** [googleapis/nodejs-storage#1891]
1) Is this a client library issue or a product issue?

    This is a client-library issue.

2) Did someone already solve this?

    I could not find anything.

3) Do you have a support contract?

    I work for Google 😄 .

#### Environment details

  - OS: Mac 12.3.1 (21E258)
  - Node.js version: 16.14.0
  - npm version: 8.3.1
  - `@google-cloud/storage` version: 5.19.3

#### Steps to reproduce

```ts
import { Storage } from '@google-cloud/storage';

async function main() {
  const opts = {
    metadata: {},
  };

  console.log('before: ', { opts });

  const storage = new Storage({
    projectId: 'sv-actions-test',
  });
  await storage.bucket('sv-actions-test').upload('package.json', opts);

  console.log('after: ', { opts });
}

main();
```

The `opts` passed to upload are modified:

```text
before: { opts: { metadata: {} } }
after: { opts: { metadata: { contentType: 'application/json' } } }
```

It's very unexpected and undocumented that the object passed to `upload` would mutate the properties of that object. This was the root cause of an [extremely difficult to debug bug](https://github.com/google-github-actions/upload-cloud-storage/issues/258) in the upload-cloud-storage GitHub Action, causing the wrong `Content-Type` to be applied to object uploads.

The workaround is to deep copy the entire object before passing it to upload. I would expect the SDK to handle this and **not** mutate objects it is given. Other functions in the SDK may have this same problem.

I believe the issue is [here](https://cs.github.com/googleapis/nodejs-storage/blob/e9d93024cea669a55e775a866591183e00b9f99f/src/file.ts#L1840).

**Comment by shaffeeullah** [comment]
Hi @sethvargo ,

Uploading an object to cloud storage requires a content type (https://cloud.google.com/storage/docs/json_api/v1/objects/insert). This is happening here: https://github.com/googleapis/nodejs-storage/blob/aab390cb3024b562f05c44ade51e71c484341feb/src/file.ts#L1844-L1852 Since no content type is being passed into the function, the library is trying to auto-detect a content type. What would be the expected behavior for you in this case? Would you have preferred that the function error and force you to pass a content type? Something else?

**Comment by sethvargo** [comment]
The MDN article might do a better job of explaining the issue than me: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#warning_for_deep_clone
