### ISSUE TITLE
Conflicting variable declaration on quickstart.js

### ISSUE THREAD

**Issue by danielduhh** [googleapis/nodejs-storage#1989]
The default function parameter conflicts with the variable declaration on line 35.

Steps to reproduce:

Uncomment line 35 on quickstart.js, change name to `dbaah-devlrel-neos`

Run `node quickstart.js`

Throws the following error

```javascript
const bucketName = 'dbaah-devrel-neos';
        ^^^^^^^^^^

SyntaxError: Identifier 'bucketName' has already been declared
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

If we remove the default value on line 17, it works.
Or, we can remove the `const` from the variable declaration and just assign the value: `bucketName = 'your-unique-bucket-name'`

**Comment by ddelgrosso1** [comment]
Hi @danielduhh thank you for bringing this up! This is actually the intended design. If you look at where the sample region tags [begin](https://github.com/googleapis/nodejs-storage/blob/9cbe987cf6fcd228d997ff3e618e67e749fc3d9b/samples/quickstart.js#L18) and [end](https://github.com/googleapis/nodejs-storage/blob/9cbe987cf6fcd228d997ff3e618e67e749fc3d9b/samples/quickstart.js#L44) you will see they do not include the main function. If a user were to copy the sample from the documentation on the web there would not be a redundant declaration. If a user runs the sample locally from the repo the second declaration by default is commented out so that arguments can be passed from the command line into the main function.

**Comment by ddelgrosso1** [comment]
Going to close this as it is the intended sample design. If you feel we should investigate a different approach feel free to reopen.
