### ISSUE TITLE
Resumable Chunked upload writes only first chunk

### ISSUE THREAD

**Issue by Chethan-sn** [googleapis/nodejs-storage#2145]
Looks like the Resumable chunked upload is saving only one chunk. Upload prompts as a success for crc32 but saves only one chunk in bucket's object. For MD5 or validation false, Upload itself is failing 

**Environment Details**
"@google-cloud/storage": "^6.9.2"
"node": 16.17.1
"npm": 8.15.0

`const {Storage} = require('@google-cloud/storage');
const fs = require("fs");
const path = require("path");

const storage = new Storage();
const bucket = storage.bucket('my-bucket');
const file = bucket.file('filename'); // file size is around 80+ MB

const chunkSize = 32 * 1024 * 1024; // 32 MB
const fileSize = fs.statSync('filepath').size;

let start = 0;
let end = chunkSize-1;
let uri;
file.createResumableUpload().then(function(data) {
    uri = data[0];
    uploadChunk();
  });

const uploadChunk = async () => {
   // console.log("uploading chunk ", start, end, uri, fileSize);
  const chunk = fs.createReadStream('filePath', {start, end});
  const chunkSizeCal =  Math.min(chunkSize, fileSize-start);
 // console.log("chunk size", chunkSizeCal);
  const options = {
    resumable: true,
    uri,
    chunkSize: chunkSize, // chunkSizeCal
    offset: start,
    validation: 'crc32'
  };

  chunk.pipe(file.createWriteStream(options))
  .on('error', (err) => {
    console.error('Error uploading chunk:', err);
  })
  .on('finish', () => {
    if (end === fileSize) {
      console.log('Upload complete!');
      return;
    }

    start = end+1;
    end = Math.min(end + chunkSizeCal, fileSize);
    uploadChunk();
  }) 

};`

**Comment by ddelgrosso1** [comment]
Hi @Chethan-sn from the looks of your code it appears that you only read a single chunk from the file `const chunk = fs.createReadStream('filePath', {start, end});` where `start = 0` and `end = chunkSize-1`. 

So if I understand correctly you only ever read 32MB of an 80MB file. This is then sent to GCS via a resumable upload where you have set the `chunkSize = 32MB`. If you wish to upload the entire file you do not need to specify a start and end when creating a read stream.

To the second part of your question, what is the error you are receiving when `validation = false`?

**Comment by Chethan-sn** [comment]
Hi @ddelgrosso1 
I am calling 'uploadChunk' method recursively by updating 'start' and 'end' variables at the end of each chunk upload.
I have a scenario where in production I get 'inputStreams' of chunks of a file. In order to mimic that, I have tried this reading of single chunk separately from a local file itself and updating start and end until the 'writeStream' all chunks are called.

Please let me know If I am trying this improperly or have misunderstood chunked upload.

**Comment by ddelgrosso1** [comment]
Hi @Chethan-sn I think I have a better understanding of what you are trying to do and I know why you are only ever getting 32MB written. 

A little bit of background when you specify `chunkSize` it tells the library to make multiple HTTP calls to the server where each request contains `chunkSize` data. When `chunkSize` is not specified a single HTTP request is made and the data is streamed into the request. Additionally, the library assumes that the entire contents to be uploaded are available ahead of time or will be provided in a single stream. 

In your example each call you are making only has 32 MB of file information in the stream and is an independent request. By setting the `offset` argument you are telling the library to fast forward in the stream to avoid sending data it already has seen. Offset is not telling the server to begin writing at X byte offset. However, since there is only 32MB in the stream at any time, after the first call in your recursion you are not sending any data because it is all being fast forwarded over.

One possibility would be to leave a stream open to your input and pipe that into the library so that as data is available the underlying streams handle all the lifting.

Please let me know if that all makes sense or you would like further clarification.

**Comment by Chethan-sn** [comment]
@ddelgrosso1 Thank you very much, That clears my confusion. I'll try this out.
I have one doubt on network error cases, How do we find out how many chunks have been successfully uploaded so that we can set appropriate 'offset' when we resume? Also, if I use the below method on 'writeStream', Could I use the below code to get 308 response for all the non-last chunks?
`.on('response', (resp) => {
    console.log("status code", resp.status);
  });`

**Comment by Chethan-sn** [comment]
@ddelgrosso1 You could probably close this issue then, My understanding about chunking was different. With the information you provided, I could change some things on my end to make it work according to my requirement I guess.

**Comment by ddelgrosso1** [comment]
@Chethan-sn to your question about a network error you should not need to set the offset manually in this case. In the internals of the library if a URI is passed as an option the library will query the server for how much data it has received and set the offset itself accordingly.

**Comment by ddelgrosso1** [comment]
Going to close this out. If you have other questions or issues @Chethan-sn please feel free to reopen.
