### ISSUE TITLE
ECONNRESET fetching https://sts.googleapis.com/v1/token

### ISSUE THREAD

**Issue by sethvargo** [googleapis/nodejs-storage#2178]
1) Is this a client library issue or a product issue?

    This is a client library issue, sometime between https://github.com/googleapis/nodejs-storage/compare/v6.5.2...v6.9.5

2) Did someone already solve this?

    I have been unable to find a previous report. This is affecting the Google GitHub action: https://github.com/google-github-actions/upload-cloud-storage/issues/320.

3) Do you have a support contract?

    I am a Googler, but customers have reported this through their Google support contracts.

#### Environment details

  - OS: `ubuntu`
  - Node.js version: `16`
  - npm version: (not sure, whatever exists on GitHub Actions by default)
  - `@google-cloud/storage` version: `v6.9.5`

#### Steps to reproduce

  1. https://github.com/google-github-actions/upload-cloud-storage/issues/320

**Comment by danielbankhead** [comment]
Hey @sethvargo 👋🏽

Looking at the [log](https://github.com/radicle-dev/heartwood/actions/runs/4597679331/jobs/8120701331#step:9:44), it appears some uploads were successful until we got `ECONNRESET`. I'm not sure why V0 of the uploader works while V1/main is having some issues [[diff](https://github.com/google-github-actions/upload-cloud-storage/compare/v0.10.4...main)], however I see the [upload config](https://github.com/google-github-actions/upload-cloud-storage/blob/b80819764124fa5579bebd061567fb77d14b44d1/src/client.ts#L215-L222) is missing a [retry strategy](https://cloud.google.com/storage/docs/retry-strategy#node.js). By default, we [retry ECONNRESET](https://github.com/googleapis/nodejs-storage/blob/be0c410ebfa25e0590d5897fed737215c57c7cf4/src/storage.ts#L267-L302) for `upload` if the `ifGenerationMatch` precondition option is set:

https://github.com/googleapis/nodejs-storage/blob/be0c410ebfa25e0590d5897fed737215c57c7cf4/src/bucket.ts#L4239-L4251

Additionally, I don't see any changes in auth (seems to be where the error is raised) and storage between the version diff that might trigger networking issues.

**Comment by sethvargo** [comment]
Hi @danielbankhead v1.0.0 works - v1.0.1 broke. That [delta](https://github.com/google-github-actions/upload-cloud-storage/compare/v1.0.0...v1.0.1) is much smaller, mostly consisting of dependency and documentation updates.

We can definitely add a RetryStrategy, but this _worked_ in previous versions of the Cloud Storage SDK. Additionally the `ECONNRESET` is coming from the call to get an auth token, not a call to upload a file.

**Comment by danielbankhead** [comment]
Deep-diving in following repos (and contacting a few colleagues) I'm not seeing anything that would cause new networking issues nor would stop prevent that error from being retried:
- storage https://github.com/googleapis/nodejs-storage/compare/v6.5.2...v6.9.5 (release: Mar 30, 2023)
- https://github.com/googleapis/google-auth-library-nodejs/compare/v8.5.2...v8.7.0 (release: Nov 9, 2022)
- https://github.com/googleapis/gcp-metadata/compare/v5.0.1...v5.2.0 (release: Jan 3, 2023)
- https://github.com/googleapis/gaxios/compare/v5.0.2...v5.1.0 (release: Mar 6, 2023)

Additionally, I'm not seeing any recent [`ECONNRESET` issues across `googleapis`](https://github.com/search?o=desc&q=org%3Agoogleapis+ECONNRESET&s=created&type=Issues).

I have a few follow-ups:
- How often is this happening on `v1.0.1` (in terms of error rate and % of customers affected)?
- Were there any outages affecting the workload(s) at the time (Github, GCP, etc.)?

> We can definitely add a RetryStrategy, but this _worked_ in previous versions of the Cloud Storage SDK. Additionally the `ECONNRESET` is coming from the call to get an auth token, not a call to upload a file, so I'm not sure that adding a retry strategy will actually affect this.

It would be retried because of the auth error would be propagated [here](https://github.com/googleapis/nodejs-storage/blob/5e4e5b6ea48b7d0edc570488de94c1db14b6b57c/src/bucket.ts#L4185-L4195) and treated as a [retryable error](https://github.com/googleapis/nodejs-storage/blob/5e4e5b6ea48b7d0edc570488de94c1db14b6b57c/src/storage.ts#L271).

**Comment by sethvargo** [comment]
> Additionally, I'm not seeing any recent [ECONNRESET issues across googleapis](https://github.com/search?o=desc&q=org%3Agoogleapis+ECONNRESET&s=created&type=Issues).

I agree - I checked first before filing an issue 😄.

> How often is this happening on v1.0.1 (in terms of error rate and % of customers affected)?

We're getting user reports on https://github.com/google-github-actions/upload-cloud-storage/issues/320. Relative to the total user base, it's very small.

> Were there any outages affecting the workload(s) at the time (GitHub, GCP, etc.)?

No - the reports are over multiple days from multiple different users. There does not seem to be a common denominator.

**Comment by danielbankhead** [comment]
Thanks for the additional details - I think the best path forward would be to add retry logic; not only to resolve this spike in errors, but as a best practice. I think this can be exposed as an `overwrite` option to `upload-cloud-storage` customers where:
- `true`: set [`IdempotencyStrategy.RetryAlways`](https://github.com/googleapis/nodejs-storage/blob/5e4e5b6ea48b7d0edc570488de94c1db14b6b57c/src/storage.ts#L608-L612) (here's a [sample](https://github.com/googleapis/nodejs-storage/blob/2cde351b21565ae8b1fd098195d6217014a3a3ff/samples/configureRetries.js#L63)) (seems like this is default behavior, and can be set as the default)
- `false`: set a `ifGenerationMatch: 0` precondition

This way, both cases are retried automatically and it's an easy, new feature for customers 🙂

Additionally, I'll work on retries directly within auth this quarter - if you'd like to review a proposal for that I can share internally once it's ready.
