### ISSUE TITLE
Cannot use on Apple Silicon due to incompatible binary dependencies in upstream packages

### ISSUE THREAD

**Issue by jimmcslim** [googleapis/nodejs-storage#2196]
#### Environment details

  - OS: macOS Monterey 12.6.1 (running on an Apple M1 Pro)
  - Node.js version: 18.16.0
  - npm version: 9.5.1
  - `@google-cloud/storage` version: 6.10.1

#### Steps to reproduce

1. Attempt to use this library on an Apple Silicon machine using a version of Node.js compiled for the ARM architecture.
2. Observe a runtime error from `dyld` `Missing symbol`.

`@google-cloud/storage` is dependent upon [`hash-stream-validation`](https://github.com/stephenplusplus/hash-stream-validation), which in turn is dependent upon [`node-fast-crc32c`](https://github.com/ashi009/node-fast-crc32c). However the binary dependencies of `node-fast-crc32c` are NOT compatible with the M1/ARM architecture.

There is [this PR](https://github.com/ashi009/node-fast-crc32c/pull/28) for `node-fast-crc32c` which would resolve [this issue](https://github.com/ashi009/node-fast-crc32c/issues/21), however it is long stalled.

Similarly there is [this issue](https://github.com/stephenplusplus/hash-stream-validation/issues/12) on `hash-stream-validation` requesting that this library also attempt to solve the problem... acknowledging that the upstream dependency appears to no longer be developed... however this issue also appears to have stalled.

I'm reminded of [this XKCD sketch](https://xkcd.com/2347/) - I certainly hope Google might consider reimplementing the functionality of these packages into your code base, and also consider including Apple Silicon in your CI/CD pipeline to ensure a positive developer experience.

Thanks!

**Comment by ddelgrosso1** [comment]
@jimmcslim thank you for raising this issue. As you noted this issue lies in our dependency tree. We have been in the process of an effort to try and reduce our usage of 3rd party libraries to avoid things like this (and reduce overall library size). While I'm not sure there is much we can do about the current lack of progress in the PRs you linked, we will certainly investigate if more compatible alternatives exist as this seems to be the quickest / easiest path. 

Unless there is enough signal from the community I would guess taking it upon ourselves to write an alternative would be a much larger / longer term undertaking. Is this issue or similar binary incompatibilities affecting your usage of any other Google Cloud SDKs?

**Comment by jimmcslim** [comment]
Thanks for the response. I thought I had upgraded across the board to 6.10.1 but perhaps I still have dependencies on the older version as well, I will investigate again and see what I can do.

**Comment by ddelgrosso1** [comment]
@jimmcslim were you able to identify if you still had an old version hanging around?
