### ISSUE TITLE
transferManager.downloadManyFiles not writing files locally

### ISSUE THREAD

**Issue by hochoy** [googleapis/nodejs-storage#2200]
#### Issue summary
I hesitated to split this into 2 issues because they are rather tightly coupled

1. Issue 1: When `prefix` is not set, `transferManager.downloadManyFiles` does not actually write files locally. This is because `destination` is `undefined`.
2. Related issue 2: When `prefix` is set, `file.download(...)` attempts to write the file, but is unable to recursively create directory structure on local machine.

#### Proposed draft PR
https://github.com/googleapis/nodejs-storage/pull/2199

#### Standard questions
1) Is this a client library issue or a product issue? - client library
2) Did someone already solve this? - it hasn't been asked yet in the Issue or Stack overflow
3) Do you have a support contract? - At work yes, but this is a personal contribution outside work

#### Environment details

  - OS: macOS Catalina
  - Node.js version: v16.15.0
  - npm version: 8.5.5
  - `@google-cloud/storage` version: 6.10.1

#### Steps to reproduce

Issue 1:
  1. Implement code example for 'downloadManyFiles' without `prefix`
  ```
  async function downloadDirectory({ bucketId, sourceDirectory }) {
    const storage = new Storage();
    const transferManager = new TransferManager(storage.bucket(bucketId));
    const options = {};

    async function downloadFolderWithTransferManager() {
      await transferManager.downloadManyFiles(sourceDirectory, options);
    }
    const res = await downloadFolderWithTransferManager();
}
  ```
  2. Running the function returns no error. However, no files are written locally, and a well-placed console.warn shows that this is because the `destination` is undefined. The draft PR contains a suggestion to always generate the destination.
  
![Screen Shot 2023-05-18 at 12 53 20 AM](https://github.com/googleapis/nodejs-storage/assets/12564636/288c95d1-4159-4d80-9c41-4dfa525d2746)
  

Issue 2:
  1. Implement same example for 'downloadManyFiles', except we now set `prefix`
  ```
  async function downloadDirectory({ bucketId, sourceDirectory }) {
    const storage = new Storage();
    const transferManager = new TransferManager(storage.bucket(bucketId));

    const options = {
      prefix: "hello",
    };
    async function downloadFolderWithTransferManager() {
      await transferManager.downloadManyFiles(sourceDirectory, options);
    }
    const res = await downloadFolderWithTransferManager();
}
  ```
  2. Running the function returns 
  ```
  ENOENT: no such file or directory, open 'hello/test-folder/'
  ```
  
![Screen Shot 2023-05-18 at 12 38 18 AM](https://github.com/googleapis/nodejs-storage/assets/12564636/cd3d169f-3d65-460e-89f8-37d9b5bc7075)
 
  This is due to the file stream at https://github.com/googleapis/nodejs-storage/blob/fe9e3a461356a7fa6e698d364174d4dc84aaa12b/src/file.ts#L2108-L2111 attempting to save a directory object locally. It appears that google storage api returns empty directory objects according to google docs here https://cloud.google.com/knowledge/kb/listing-only-objects-using-gsutil-and-not-directories-000004568. The draft PR proposes to filter out these empty directory objects from the final write.

Thanks, it is my first issue and fork of the repo! Open to feedback. I've already signed the CLA, but kept the PR as draft until the codeowner reviews the issue/intention of the existing design.

**Comment by ddelgrosso1** [comment]
Hi @hochoy thanks for opening this issue! We have been interested in hearing feedback about `TransferManager` since we initially implemented it late last year and yours is the first we have received. 

Regarding the first issue you raised about nothing being written when there is no prefix this was the intended design (and not saying it is necessarily the best). As you noted / saw under the hood `TransferManager` utilizes a call to `file.download`. When `file.download` is called without a destination it is designed to download the file into memory. Our intention was to mimic this behavior in `TransferManager` but looking at it now I can see how this isn't clear. I also wonder about the use case of downloading many files into memory. I am apt to agree with you in removing the conditional check and defaulting to the file name if nothing else is provided. 

As for the second issue this is a good catch and I think the fix looks good. I will just do some local testing to verify.

Please feel free to take your PR out of draft state if you feel it is ready for review and I will comment there accordingly. We much appreciate the contribution.

**Comment by hochoy** [comment]
Thanks, Ill take it out of draft.

Regarding your first issue comment, I had suspected that might have been the intent. Writing files to the local machine can often be undesirable to the user of the `TransferManager`. 

However, I'm not sure how I can access the files downloaded in memory? `files.download()` expects a second `cb` param, but it seems it is not accessible from `TransferManager.downloadManyFiles()`.

**Comment by stabback** [comment]
Hey there, any movement on this?  As is, it doesn't look like you can use `downloadManyFiles` to download files to the local filesystem.

**Comment by convers39** [comment]
This API is confusing and a little useless. The response object gives you `Buffer`. Even if you can write the Buffer into a local file, you still need the filename at least (or other metadata) about the file object, not just the Buffer, and it seems no way to retrieve that metadata alone through this API. The `passthroughOptions.destination` seems can not define a target directory, instead it will create a file.


```ts
      const localPath = path.resolve(process.cwd(), `dest`);
      // const targetReleaseFolders = [''];
      const client = await this.getStorageClient(projectId, bucket);
      const downloadRes = await client.downloadManyFiles('active', {
        // passthroughOptions: {
        //   destination: localPath, 
        // },
      });

      logger.info(`downloadRes`, { downloadRes });
      if (Array.isArray(downloadRes)) {
        downloadRes.map((res, idx) => {
          writeFileSync(path.resolve(localPath, `file-${idx}`), res[0]);
        });
      }

```

The documentation and code example also do not help at all. For those who want to download multiple files, I would suggest the humble `download` API instead of the transfer manager.

```ts
      const [files] = await storage.bucket(bucketName).getFiles({ prefix: 'folder' });

      console.log('files', files);
      const res = await Promise.all(
        files.map(async (f) => {
          await client
            .file(f.name)
            .download({ destination: path.resolve(localPath, f.name) });
        }),
      );

```

**Comment by ddelgrosso1** [comment]
Hi @stabback and @convers39 I will circle back on this and try and pick up where the previous PR left off. I will update accordingly.

**Comment by Snugug** [comment]
Hey @ddelgrosso1, sorry for commenting on a closed issue, but I'm running into the same issue in `@google-cloud/storage` v`7.12.0`.  Strangely enough, though, it's not _consistently_ failing.

I've got two folders, each with subfolders, in storage, with files in each. I'm calling `await downloadFiles('');` and the first folder that's downloaded, it's subfolder is downloaded as expected. The second folder all of its immediate children are properly downloaded, but the moment it tries to write the first file to its subfolder, it fails with "no such file or directory" and an `ENOENT` error.

**Comment by ddelgrosso1** [comment]
@Snugug if you hit the same problem again would you mind opening a new issue so that I can take a look / resolve it?
