### ISSUE TITLE
Private identifiers warning

### ISSUE THREAD

**Issue by tfang17** [googleapis/nodejs-storage#2216]
#### Environment details

  - OS: Mac
  - Node.js version: 16.20.0
  - npm version: 9.7.1
  - `@google-cloud/storage` version: 6.11.0

#### Steps to reproduce

Getting warning:

```node_modules/@google-cloud/storage/build/src/crc32c.d.ts:68:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

68     #private;
       ~~~~~~~~

node_modules/@google-cloud/storage/build/src/file.d.ts:254:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

254     #private;
        ~~~~~~~~

node_modules/@google-cloud/storage/build/src/hash-stream-validator.d.ts:20:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

20     #private;
       ~~~~~~~~

**Comment by ddelgrosso1** [comment]
@tfang17 I'm assuming this is when you are building your own application which includes the storage library? Can you share the relevant portions of your `tsconfig`?

**Comment by tfang17** [comment]
Yes it is:

```{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "module": "commonjs",
        "noImplicitReturns": true,
        "noImplicitAny": false,
        "noUnusedLocals": true,
        "outDir": "functions/build",
        "skipLibCheck": true,
        "sourceMap": true,
        "strict": false,
        "target": "es6"
    },
    "compileOnSave": true,
    "exclude": ["functions/src/sandbox.ts"],
    "include": ["functions/src"]
}
```

**Comment by ddelgrosso1** [comment]
How are you invoking the compiler? I was only able to reproduce this when specifying input files manually, i.e. `tsc index.ts` [which is expected behavior](https://github.com/microsoft/TypeScript/issues/6591#issuecomment-174343747) as the `tsconfig.json` is not considered in this situation. When I used your configuration and invoked the compiler with `tsc -p .` I have no warnings which is what I would expect since private identifiers should be available with `es6`.

**Comment by tfang17** [comment]
Got it, that makes sense!
