### ISSUE TITLE
Setting metadata seems really difficult to reason with.

### ISSUE THREAD

**Issue by gauntface** [googleapis/nodejs-storage#222]
I was just trying to set the metadata to files and frankly couldn't figure out what was going on. I'm still not 100% but I think this invalid:
```
file.setMetadata({
  'example-key': 'example-value',
});
```

Instead it's meant to be:

```
file.setMetadata({
  metadata: {
    'example-key': 'example-value',
  }
});
```

Reason being that custom metadata *has* to moved out of the top level set of metadata values.

If this is the case, I would love two changes made to the API to make this easy to reason with:

1. Enforce a strict check on the metadata value such that custom values *cannot* be used on the top level metadata object.
1. *Bit of a stretch but I would like it* Add a setCustomMetadata() method to avoid this weirdness around wrapping metadata with a metadata key.

**Comment by gauntface** [comment]
Another point of confusion I hit was setting custom metadata when saving a file.

This silently drops the metadata (same as above):
```
file.save("hello", {
    contentType: 'application/json',
    metadata: {
        'example-key': 'example-value',
    }
})
```

This works:

```
file.save("hello", {
    contentType: 'application/json',
    metadata: {
        metadata: {
          'example-key': 'example-value',
        }
    }
})
```

**Comment by jeffposnick** [comment]
Chiming in here—irrespective of *why* there is that double-`metadata` key, there's a lack of examples that illustrate how to use `metadata.metadata` and `gzip: true` to set values that are useful for CDN-type hosting setups.

I filed https://github.com/googleapis/nodejs-storage/pull/225 to update one of the examples to include those fields. Feel free to close that and make changes elsewhere if you think there's a better place to illustrate it.

**Comment by stephenplusplus** [comment]
> Enforce a strict check on the metadata value such that custom values cannot be used on the top level metadata object.

I don't think we can go this route, as we'd have to whitelist property names, which could evolve without our knowing.

> Bit of a stretch but I would like it Add a setCustomMetadata() method to avoid this weirdness around wrapping metadata with a metadata key.

I'm neutral on this. I don't mind it, but I don't know if it will make anything more clear for users. The confusion is mostly that two different metadata concepts exist. Once they know that, it's not too hard to communicate the right type to us. But I agree it's weird, so if we want to just solve the weirdness, this is okay.

**Comment by gauntface** [comment]
@stephenplusplus yeah, it kind of feels like "file options" and "file metadata" are being merged into one place but have different meaning / uses.

**Comment by stephenplusplus** [comment]
Across our APIs, `metadata` refers to the remote description of a resource. So for GCS, `file.getMetadata()` returns https://cloud.google.com/storage/docs/json_api/v1/objects.

The weird part is that the resource representation of a GCS `Object` includes a `metadata` property. That means we end up with what we refer to as `metadata` containing a `metadata` property: `metadata.metadata`.

We have methods built around *our* metadata, `getMetadata()` and `setMetadata()`. So, we end up with what looks like poor design:

```js
file.setMetadata({
  metadata: {
    // Your metadata here!
  }
})
```

But that's also where other values go:

```js
file.setMetadata({
  // Non-custom metadata.
  contentType: 'application/json',

  metadata: {
    // Your **custom!** metadata here!
    // myCustomKey: 'my-custom-value'
  }
})
```

I think this is weird, but I'm not sure of the most helpful fix. Maybe some more input could help?

**Comment by stephenplusplus** [comment]
It's rare a complaint for this comes up, and since we're stuck for ideas, maybe it's just an uncommon, short-lived pain point?

**Comment by repentsinner** [comment]
I ran into this recently, and would suggest that rather than changing the APIs maybe just add an explicit user metadata sample for any of the contexts that support it? It's very loosely hinted at in some of the existing samples such as https://github.com/googleapis/nodejs-storage/blob/master/samples/files.js#L257

The docs do touch on this as well (https://googleapis.dev/nodejs/storage/latest/File.html#setMetadata), but don't explicitly call out that the nested nature of the term 'metadata' might be a gotcha for those unfamiliar with this. Perhaps some clearer wording to suggest that `metadata.metadata` can be considered as `metadata.user_metadata` or `metadata.context_metadata`, rather than GCS-specific metadata would help?

I'd also suggest that the [`file.js`](https://googleapis.dev/nodejs/storage/latest/File.html#setMetadata-examples) example that is embedded in the docs could be included in the [samples directory](https://github.com/googleapis/nodejs-storage/tree/master/samples) for those of us who read docs as a last resort :) This code most clearly illustrates the difference between reserved GCS properties and custom properties.
