### ISSUE TITLE
what is the page limit of getFiles with autoPaginate=false 

### ISSUE THREAD

**Issue by convers39** [googleapis/nodejs-storage#2429]
In the official example below, it shows that using autoPaginate = false meanwhile tracking a cursor of pageToken.

https://github.com/googleapis/nodejs-storage/blob/36d27212848a1002cc0fa699364a446c4f8d25e4/samples/listFilesPaginate.js#L32-L48

It implies there is a limit to how many files it could get in one request, but I could not find any documentation about it.

Somehow I could not find the implementation of `getFiles` by searching `getFiles` in this repo, does anyone have any idea about the `getFiles` page limit?

And if there is a limit anyway, why not suggest using stream instead of the example above? The example seems not very practical as in most cases you don't know how many pages there are.

**Comment by ddelgrosso1** [comment]
Hi @convers39 the recommended upper limit is 1000. However, the API may choose to return less than the requested number. See the documentation for `maxResults` [here](https://cloud.google.com/storage/docs/json_api/v1/objects/list#parameters). You are correct that you would not know the number of pages in advance which is why the documentation recommends checking for the presence of `nextPageToken` on the response. 

The implementation for `getFiles` can be found [here](https://github.com/googleapis/nodejs-storage/blob/36d27212848a1002cc0fa699364a446c4f8d25e4/src/bucket.ts#L2587). We also provide the function `getFilesStream` which will stream the results.

**Comment by convers39** [comment]
Hi @ddelgrosso1 , thank you for your explanation.

> the recommended upper limit is 1000. However, the API may choose to return less than the requested number

I see, so it would be better to use `autoPaginate:false` with `maxResults` together. And if the files are about to be over 1000, it is better to retrieve them with `nextPageToken`, or `getFilesStream`.
