### ISSUE TITLE
Cloud storage File API size is a string (it should be a number)

### ISSUE THREAD

**Issue by iislucas** [googleapis/nodejs-storage#568]
The type of `bucket.file(filePath).getMetadata()).size` is a string, it should presumably be a number.

#### Environment details

  - OS: Mac OS 10.13.6
  - Node.js version: v8.11.3
  - npm version: 6.2.0
  - `@google-cloud/storage` version: 2.3.4

#### Steps to reproduce

  1. `let instance = new storage.Storage(); let bucket = instance.bucket(bucketName);`
  2. `console.log(typeof((await bucket.file(filePath).getMetadata()).size));`
  3. Observe that 'string' is printed.

**Comment by iislucas** [comment]
hrm... that seems bad for clients who then have to wrap the numbers in parseInt everywhere (for this case)....  But I do see it's tricky because JS number only supports 53 bit integers, and so you'd either have to say some unsigned long's become numbers (for when the number will never be too big) while others become strings (where the number may be too big)... Or move to something like BigInt: https://developers.google.com/web/updates/2018/05/bigint 

(the JSON API link you shared seems to go to a generic object `get` from which it's not clear why the size parameter would be a string (there is no mention of the size parameter in that page)... perhaps you sent the wrong link?)

**Comment by stephenplusplus** [comment]
`file.getMetadata()` calls ["get"](https://cloud.google.com/storage/docs/json_api/v1/objects/get), which returns an [`Object` resource](https://cloud.google.com/storage/docs/json_api/v1/objects#resource), which is what @kinwa91 linked.

I confirmed we return a string, and also confirmed the API itself returns a string, which is why we do. You can try this with a CURL request, or using the ["get"](https://cloud.google.com/storage/docs/json_api/v1/objects/get) page's "Try this API" section on the right.

I agree it would make sense that it should be a JavaScript `Number` object, but probably for the reasons you mentioned, it's housed in a string so we don't go out of bounds.

As a rule for a guarantee of consistency with the upstream API, we don't override what it gives us, so we wouldn't want to dig in and selectively replace values.

@kinwa91 is there any resolution we can find here? The API docs seem to list the response value's intended type, as opposed to what it actually comes across the wire as. That can be a bit confusing when we're trying to help a user understand the response they will get from us. Maybe the API docs could show both?:

#### Before
![image](https://user-images.githubusercontent.com/723048/50778161-403c3900-126b-11e9-82d5-12bf25a8c5bb.png)

#### After
<img width="713" alt="screen shot 2019-01-07 at 10 58 28 am" src="https://user-images.githubusercontent.com/723048/50778130-34507700-126b-11e9-9533-cfa8e25e3ac6.png">

#### Or
![image](https://user-images.githubusercontent.com/723048/50778292-96a97780-126b-11e9-93f7-0194c6f6787d.png)

Wish I could think of something better, so input definitely welcome! :)

**Comment by iislucas** [comment]
Yeah, a tricky one... I don't think I would have found that `file.getMetadata()` calls get and thus returns an object that is represented as a string... perhaps a page to document the returned object by file.getMetadata(), with the fields and typed would be the clearest? 

Also, +1 for your suggestions. I'd add a note in the description: "Note that the `long` is represented as a `string` in Javascript, rather than a Javascript `number`."

**Comment by kinwa91** [comment]
I agree that we should change the type in the REST docs to make it explicit that it's returning a string representation of `long` and that we should not cast the type in this library. I'll file an issue upstream to try and get the docs sorted out. 

Another thing we can do is probably instead of linking to the REST docs, define the types properly in the jsdoc in our library. Although it could potentially hard to maintain in the event that the API service has changed. @stephenplusplus What do you think?

**Comment by stephenplusplus** [comment]
Sorry for the delay. We've avoided duplicating as much as possible, because of that exact reason. If we can link to a definitive source of truth, that's usually the safest way to go.

**Comment by stephenplusplus** [comment]
The upstream docs don't seem to have been changed, although I don't believe this issue is in charge of tracking that. I'm going to close, but please re-open if necessary.
