### ISSUE TITLE
Setting an encryption key for a signed URL.

### ISSUE THREAD

**Issue by atmortensen** [googleapis/nodejs-storage#592]
I think this is a feature request, unless it is already in and I'm just using it wrong. I have been trying to create a writable signed url with a customer supplied encryption key, but it doesn't seem to work. 
```
bucket
    .file(fileName)
    .setEncryptionKey(myEncryptionKey)
    .getSignedUrl({
        expires: Date.now() + 1000 * 60 * 60,
        action: 'write'
    })
```
That works fine for uploading the file, but when I check the file in the console it says "Google-managed key"

**Comment by stephenplusplus** [comment]
@frankyn I think I could use some clarity on expected behavior here :) I've uploaded a file using a customer-supplied encryption key, and the console confirms it is encrypted as such. Then, I create a signed URL for a `PUT` operation. When I `PUT` data to it _without_ the key, it overwrites it, and shows in the console as "Google-managed key". If I try to write to it with the `x-goog-encryption-*` headers, it will fail:

```
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
```

**Comment by frankyn** [comment]
Hi y'all,

I'll dive deeper next week if this doesn't help unblock the issue.

You need to define x-goog-encryption-algorithm as an extensionHeader with the value of AES256.
```
storage
  .bucket(bucketName)
  .file('test')
  .getSignedUrl({
        expires: Date.now() + 1000 * 60 * 60,
        action: 'write',
	extensionHeaders: {'x-goog-encryption-algorithm': 'AES256'}
    }, function(err, url) { console.log(url);});
```

The other two headers should not be part of the signed URL (`x-goog-encryption-key` and `x-goog-encryption-key-sha256`). These two headers are not used by GCS to verify the signature. 

Per: https://cloud.google.com/storage/docs/access-control/signed-urls#about-canonical-extension-headers

**Comment by atmortensen** [comment]
@frankyn So that works, but it requires me to add the `x-goog-encryption-key` and `x-goog-encryption-key-sha256` headers on my request to the signed URL on the front end. I don't really want the front end to have my encryption key. I was hoping that I could create a signed URL that stored my encryption key, but now that I'm thinking it though, that would require Google to store the customer supplied encryption key until the file is sent to the signed URL. That probably defeats the whole purpose of having a customer supplied encryption key, huh?

**Comment by frankyn** [comment]
Hi @atmortensen,

Could you tell me about your end goal with using customer supplied encryption keys with a signed URL?

If you expect a CSEK in the signed URL, you'd be exposing it in the client side code.

**Comment by stephenplusplus** [comment]
I think all is working as expected, we just didn't figure out exactly how to do it :)

**Comment by adevine** [comment]
I know this is an old issue, but this was really helpful to me in figuring out hot to use signed URLs with customer-supplied encryption keys. Don't know if something has changed since @frankyn 's response above, but when generating a Signed Upload URL to be used with a customer-supplied encryption key, I had to include **all** of the required `x-goog-...` headers : `x-goog-encryption-algorithm`, `x-goog-encryption-key` and `x-goog-encryption-key-sha256` in the `extensionHeaders` option when calling `getSignedUrl`, and the doc seems to say as much: https://cloud.google.com/storage/docs/authentication/canonical-requests#required-headers

If I left off `x-goog-encryption-key` or `x-goog-encryption-key-sha256` when creating the signed URL I got the following error when I tried to use that signed URL to upload a file with those headers:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<Error>
  <Code>MalformedSecurityHeader</Code>
  <Message>Invalid argument.</Message>
  <Details>Your request has a malformed header. Header must be signed.</Details>
  <ParameterName>x-goog-encryption-key-sha256</ParameterName>
</Error>
```
