### ISSUE TITLE
Update incorrect documentation for getSignedUrl

### ISSUE THREAD

**Issue by zackify** [googleapis/nodejs-storage#735]
![image](https://user-images.githubusercontent.com/449136/59153190-9d017280-8a08-11e9-93c4-3ddb9c3af8e9.png)

The documentation for `File.getSignedUrl` https://cloud.google.com/nodejs/docs/reference/storage/2.5.x/File#getSignedUrl

incorrectly says contentType is optional. It is not, after an hour of debugging I realized from stackoverflow, that you must set the content type when making the url, or the upload fails with a 403 every time.

**Comment by AVaksman** [comment]
@zackify Thank you for reporting this issue.
The documentation is correct, but doesn't paint the full picture.
`contentType` (as well as `contentMd5` and `extensionHeaders`) are optional parameters, however what documentation is lacking is that these parameters and values **must** be mirrored **both ways** as headers with the same values. Meaning just like corresponding HTTP header mus be passed if the parameter was set so to a corresponding HTTP header must not be provided if it was not set in `getSignedUrl` method. Otherwise it will fail with signature mismatch message.

As an example:
Getting a `write` `signedUrl` without a `contentType` as below
```ts 
  const url = await file.getSignedUrl({
    action: 'write',
    expires: Date.now + 600000
  });
```
will work fine in the scenario of
```ts
  const request = require('request');
  const writableStream = request.put(url);
  writableStream.write('Hello ', console.error);
  writableStream.write('world', console.error);
  writableStream.end('!');
```
but will fail if piped from a `readableStream`:
```ts
  const readable = getReadableSomehow();
  const writableStream = request.put(url);
  readable.pipe(writableStream);
```
because request module automatically sets `content-type` header on `'pipe'` event via `mime.lookup`.
