### ISSUE TITLE
Not able to upload image to Google Cloud Storage from Google Cloud functions, not getting any success or error response.

### ISSUE THREAD

**Issue by akashgangrade** [googleapis/nodejs-storage#783]

**Comment by akashgangrade** [comment]
`storage
         .bucket(bucketName)
         .upload(localFilePath)
         .then(() => {
           console.log(`${fileName} uploaded to ${bucketName}.`);
         })
         .catch(err => {
           console.error('ERROR:', err);
         });`

**Comment by stephenplusplus** [comment]
@akashgangrade would you be able to fill out the new issue template?

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-storage/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/storage` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by vishald123** [comment]
Hi @akashgangrade, please refer [Tips & Tricks](https://cloud.google.com/functions/docs/bestpractices/tips#ensure_http_functions_send_an_http_response). You can try following way.

```js
const {Storage} = require ('@google-cloud/storage');
const storage = new Storage ();
const escapeHtml = require ('escape-html');

exports.myFunction = async (req, res) => {

  const bucketName = '[BUCKET_NAME]'; //TO DO
  const localFilePath = '[FILEPATH]'; //TO DO

  await storage
    .bucket (bucketName)
    .upload (localFilePath)
    .then (() => {
      res.send (`${escapeHtml (localFilePath + 'uploaded to' + bucketName)}`);
    })
    .catch (err => {
      res.send ('ERROR:', err);
    });
};

```

Please let me know if it works for you.
