### ISSUE TITLE
feature request: allow stream in File.save

### ISSUE THREAD

**Issue by fiws** [googleapis/nodejs-storage#98]
To avoid some boilerplate code with streams it would be nice to be able to pass a stream to `File.save`

## Example
```js
const read = fs.createReadStream('./somefile.bin');
const file = bucket.file(`test.bin`);
await file.save(read);
// do other stuff
```
This would be very useful when working with promises.

**Comment by callmehiphop** [comment]
@fiws have you thought about using something like [stream-to-promise](https://www.npmjs.com/package/stream-to-promise)? I think we're of the opinion that the streaming and non-streaming APIs shouldn't connect in that way.

**Comment by stephenplusplus** [comment]
I would agree that `stream-to-promise` seems like the right way to go. I would be convinced otherwise if in the average app, we're the only API not accepting streams as an argument. That doesn't match my experience so far, which is why I'm slanted towards letting the module ecosystem solve this-- since it's probably not just us, a user would need a module like `stream-to-promise` for use with those other APIs.

However, I'm contradicting myself by suggesting `stream-to-promise`. If a lot of users are finding that useful, then it stands to reason it would be best to give users what they want.

What do you think @fiws? Obviously, you asked for the feature, but have you been able to make this work without the suggested change in a way that's not too cumbersome? Or do you feel even more strongly we should support this as time passed?

Considering the above, I would be okay with a PR for this, although I don't consider it urgent. Its value might increase in time.

**Comment by fiws** [comment]
Thanks for the response.

`stream-to-promise` is better than the awkward wrapper I have build. Thanks for suggesting that. It's good enough for my use case for now. :)

I would really like to see node figure out their promise/callback/event/stream mess. It feels like we're slowly moving towards a more promise based node core starting with `util.promisify`. 

You can close this issue if it bothers you. I would still like the feature though.

**Comment by stephenplusplus** [comment]
I'll mark it the issue with "help wanted", so if anyone beats us to implementing it, great!

**Comment by stephenplusplus** [comment]
For now, I think it's best to let the API stand, as-is. If you want to PR it, it should be a non-harmful change, although I don't think there is much demand from the community at this time. We can always re-open if we hear more requests for this.
